name: Run Stan Script on Workdays

on:
  schedule:
    # Runs at 6 PM CET (17:00 UTC in winter, 18:00 UTC in summer) on workdays (Mon-Fri)
    - cron: '0 17 * * 1-5'
    # Runs at 9 PM CET (20:00 UTC in winter, 21:00 UTC in summer) on workdays (Mon-Fri)
    - cron: '0 20 * * 1-5'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-stan:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests logging yfinance=0.2.54

      # Step 4: Run the stan.py script and save output to a file
      - name: Run stan.py
        run: |
          # Run the script and save output to a file
          python stan.py > result.txt

      # Step 5: Print the result file as an artifact
      - name: Print result file
        run: |
          cat result.txt
        
